### ISSUE TITLE
Improper dihedrals for bmim cation

### ISSUE THREAD

**Issue by matteobusato** [vladislavivanistsev/RTIL-FF#14]
Hi,
thanks a lot for the topologies, your work has been very useful for me.
I have a question about the improper dihedrals of the bmim cation. In the prof. Padua github page I've seen that they are:

#improper imidazolium ring
CR  CW  NA  CT   opls   0.0000    8.3680    0.0000    0.0000
CR  CW  NA  HA   opls   0.0000    8.3680    0.0000    0.0000
NA  NA  CR  HA   opls   0.0000    9.2048    0.0000    0.0000
NA  NA  CR  CT   opls   0.0000    9.2048    0.0000    0.0000
NA  CW  CW  HA   opls   0.0000    9.2048    0.0000    0.0000

but in your topology they are:

   5   13    1    3    5       0.000       8.370       0.000       0.500 ; CW C1 NA CR  **
   7    9    2    3    5       0.000       8.370       0.000       0.500 ; CW C1 NA CR  ** 
   2    4    3    1    5       0.000       9.205       0.000       0.500 ; NA HA CR NA  **
   6    7    5    1    5       0.000       9.205       0.000       0.500 ; HA CW CW NA  **
   5    8    7    2    5       0.000       9.205       0.000       0.500 ; CW HA CW NA  **

so the atoms taking part to the dihedrals seem different. Is it just a mistake or there is something I am missing?
Thank you in advance for your answer, this would really help me.

Matteo

**Comment by vladislavivanistsev** [comment]
Hi Matteo,

It is probably my mistake. Yet, let me check this out.
I shall return to work in August. Could you please remind me about this question in two weeks.

Regards,
Vladislav
